---
ReportDefinitions:
- reportName: TransactionStatusReport
  summary: Transaction Status Report
  version: 1.0.0
  moduleName: rainmaker-common
  sourceColumns:
  - name: tenant_id
    label: ULB
    type: string
    source: pt
    total: false
  - name: gateway
    label: Gateway
    type: string
    source: pt
    total: false
  - name: txn_status
    label: Transaction Status
    type: string
    source: pt
    total: false
  - name: txn_status_msg
    label: Transaction Status Message
    type: string
    source: pt
    total: false
  - name: txn_amount
    label: Transaction Amount
    type: string
    source: pt
    total: false
  - name: gateway_txn_id
    label: Gateway Transaction Id
    type: string
    source: pt
    total: false
  - name: gateway_status_code
    label: Gateway Status Code
    type: string
    source: pt
    total: false
  - name: gateway_status_msg
    label: Gateway Status Message
    type: string
    source: pt
    total: false
  - name: gateway_payment_mode
    label: Gateway Payment Mode
    type: string
    source: pt
    total: false
  - name: consumer_code
    label: Consumer Code
    type: string
    source: pt
    total: false
  - name: module
    label: Module
    type: string
    source: pt
    total: false
  - name: txn_initiate_time
    label: Transaction Initiation Time
    type: string
    source: pt
    total: false
  - name: txn_last_updated_time
    label: Transaction Last Updated Time
    type: string
    source: pt
    total: false
  searchParams:
  - name: fromDate
    label: From Date
    type: epoch
    source: pt
    isMandatory: false
    searchClause: and date(to_timestamp(created_time/1000)) >= date(to_timestamp($fromDate/1000))
  - name: toDate
    label: To Date
    type: epoch
    source: pt
    isMandatory: false
    searchClause: and date(to_timestamp(created_time/1000)) <= date(to_timestamp($toDate/1000))
  - name: transactionStatusInput
    label: Transaction Status
    type: singlevaluelist
    pattern: 'list://FAILURE:Failure,SUCCESS:Success,PENDING:Pending'
    source: pt
    isMandatory: false
    searchClause: AND ept.txn_status = $transactionStatusInput
  - name: moduleInput
    label: Module
    type: singlevaluelist
    pattern: 'list://BPA%:BPA,PT%:PT,WS%:WS,TL%:TL,FSM%:FSM,MR%:MR'
    source: pt
    isMandatory: false
    searchClause: AND ept.module like $moduleInput
  query: |
      select tenant_id,gateway,txn_status, txn_status_msg,txn_amount,gateway_txn_id, gateway_status_code, gateway_status_msg, gateway_payment_mode,consumer_code,"module",to_char(to_timestamp(created_time/1000), 'YYYY-MM-DD') txn_initiate_time,to_char(to_timestamp(last_modified_time /1000), 'YYYY-MM-DD') txn_last_updated_time from eg_pg_transactions ept where 1=1